updated in TaskDevelopment
sasminqualminds/Task pull request #1
Opened 2024-05-01 06:20 UTC by sasminqualminds

made changes in variable naming convention.

2024-05-01 14:04 UTC, qm-bhupal commented on NumberReverse/Program.cs
> +            string empty = "";
use int and give a proper name like reverseNumber

2024-05-01 14:10 UTC, sasminqualminds commented on NumberReverse/Program.cs
> +            string empty = "";
Ok

2024-05-06 09:08 UTC, qm-bhupal requested changes

2024-05-06 09:08 UTC, qm-bhupal commented on NumberReverse/Program.cs
> +            int reverseNumber;
write the logic using int, don't use string

2024-05-07 05:07 UTC, sasminqualminds commented on NumberReverse/Program.cs
> +            int reverseNumber;
Ok

2024-05-08 11:53 UTC, merged